"""create funnel events table

Revision ID: 93a1942d3f41
Revises: 07e2d5d23c76
Create Date: 2026-04-04 13:33:55.334930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a1942d3f41'
down_revision: Union[str, None] = '07e2d5d23c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_source', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_events_created_at'), 'funnel_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_events_event_type'), 'funnel_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_funnel_events_id'), 'funnel_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funnel_events_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_event_type'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_created_at'), table_name='funnel_events')
    op.drop_table('funnel_events')
    # ### end Alembic commands ###
