"""create vacancy candidate matches table

Revision ID: df42314f3090
Revises: 93a1942d3f41
Create Date: 2026-04-04 14:16:34.404185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df42314f3090'
down_revision: Union[str, None] = '93a1942d3f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_candidate_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_candidate_matches_candidate_id'), 'vacancy_candidate_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_vacancy_candidate_matches_created_at'), 'vacancy_candidate_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_candidate_matches_employer_id'), 'vacancy_candidate_matches', ['employer_id'], unique=False)
    op.create_index(op.f('ix_vacancy_candidate_matches_id'), 'vacancy_candidate_matches', ['id'], unique=False)
    op.create_index(op.f('ix_vacancy_candidate_matches_status'), 'vacancy_candidate_matches', ['status'], unique=False)
    op.create_index(op.f('ix_vacancy_candidate_matches_vacancy_id'), 'vacancy_candidate_matches', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_candidate_matches_vacancy_id'), table_name='vacancy_candidate_matches')
    op.drop_index(op.f('ix_vacancy_candidate_matches_status'), table_name='vacancy_candidate_matches')
    op.drop_index(op.f('ix_vacancy_candidate_matches_id'), table_name='vacancy_candidate_matches')
    op.drop_index(op.f('ix_vacancy_candidate_matches_employer_id'), table_name='vacancy_candidate_matches')
    op.drop_index(op.f('ix_vacancy_candidate_matches_created_at'), table_name='vacancy_candidate_matches')
    op.drop_index(op.f('ix_vacancy_candidate_matches_candidate_id'), table_name='vacancy_candidate_matches')
    op.drop_table('vacancy_candidate_matches')
    # ### end Alembic commands ###
